### ISSUE TITLE
Incompatibe S3A URLs

### ISSUE THREAD

**Issue by dgloeckner** [minio/spark-select#11]
When _not_ using spark-select specific formats I can use s3a URLs without having to provide the endpoint, which is already configured in the `spark.hadoop.fs.s3a.endpoint` property.

Following read works fine
```
spark.read.parquet("s3a://myBucket/aFile.parquet")
```

Using the same URL with minioSelectParquet format causes the exception given below.

```
spark.read.format("minioSelectParquet").schema(schema).load("s3a://myBucket/aFile.parquet").show
```

Finally, when explicitly providing region and endpoint in the location it seems to work.
```
spark.read.format("minioSelectParquet").schema(schema).load("s3a://s3.us-east-1.localhost:9000/myBucket/aFile.parquet").show
```

```
scala> spark.read.format("minioSelectParquet").schema(schema).load("s3a://myBucket/aFile.parquet").show
java.lang.IllegalArgumentException: Invalid S3 URI: hostname does not appear to be a valid S3 endpoint: s3a://myBucket/aFile.parquet
  at com.amazonaws.services.s3.AmazonS3URI.<init>(AmazonS3URI.java:112)
  at com.amazonaws.services.s3.AmazonS3URI.<init>(AmazonS3URI.java:62)
  at com.amazonaws.services.s3.AmazonS3URI.<init>(AmazonS3URI.java:48)
  at io.minio.spark.select.SelectParquetRelation.getRows(SelectParquetRelation.scala:80)
  at io.minio.spark.select.SelectParquetRelation.tokenRDD(SelectParquetRelation.scala:122)
  at io.minio.spark.select.SelectParquetRelation.buildScan(SelectParquetRelation.scala:134)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$10.apply(DataSourceStrategy.scala:293)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$10.apply(DataSourceStrategy.scala:293)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:326)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:325)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProjectRaw(DataSourceStrategy.scala:403)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProject(DataSourceStrategy.scala:321)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy.apply(DataSourceStrategy.scala:289)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
  at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
  at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
  at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:78)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:75)
  at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
  at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
  at scala.collection.Iterator$class.foreach(Iterator.scala:891)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
  at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
  at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1334)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:75)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:67)
  at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
  at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:73)
  at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:69)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:78)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:78)
  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3365)
  at org.apache.spark.sql.Dataset.head(Dataset.scala:2550)
  at org.apache.spark.sql.Dataset.take(Dataset.scala:2764)
  at org.apache.spark.sql.Dataset.getRows(Dataset.scala:254)
  at org.apache.spark.sql.Dataset.showString(Dataset.scala:291)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:751)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:710)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:719)
  ... 49 elided
```

**Comment by harshavardhana** [comment]
Not meant to be used s3a that is an entirely different connector. Use it as `s3://` as documented.

**Comment by harshavardhana** [comment]
what you seem to be missing is to set `fs.s3a.path.style.access`

**Comment by dgloeckner** [comment]
@harshavardhana so should it work woth S3A URI scheme or not? According to the following documentation, S3A is the FS implementation which offers the highest performance. It also mentions that S3 is deprecated. I have `fs.s3a.path.style.access` configured in my spark defaults and this works fine when not using minioSelectParquet format.

Here's the article mentioning deprecation of S3.
https://web.archive.org/web/20170718025436/https://aws.amazon.com/premiumsupport/knowledge-center/emr-file-system-s3/

**Comment by morningmemo** [comment]
+ not working yet

**Comment by plamenmpetrov** [comment]
@dgloeckner  @morningmemo @harshavardhana

I found that [Release v2.1](https://github.com/minio/spark-select/releases/tag/v2.1) does not have the support for `s3a`.  When I was including the release in [this](https://github.com/minio/spark-select#spark-shell-pyspark-or-spark-submit) way, I was getting the same error as @dgloeckner . It looks like the support for `s3a` was added after v2.1 ([here](https://github.com/minio/spark-select/commit/4dd246ea7b5045257fa08c0f445b1b29e0b6f20d)), but this is not included in a release? After cloning the master branch, and building from source, I am able to use `s3a`.
