### ISSUE TITLE
Error when use spark count() function 

### ISSUE THREAD

**Issue by ogerasymenko** [minio/spark-select#13]
Hi. I'm trying use spark-select_2.11 package and got error when try to call count() function.

`java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)

printenv | grep JAVA
JAVA_HOME=/opt/java/openjdk
JAVA_VERSION=jdk8u242-b08
SPARK_VERSION=2.4.5
HADOOP_VERSION=3.1.2

Python version:
2.7.16 (default, Nov 15 2019, 19:32:34

Spark additional jars:
aws-java-sdk-1.11.534.jar
aws-java-sdk-core-1.11.534.jar
aws-java-sdk-kms-1.11.534.jar
aws-java-sdk-s3-1.11.534.jar
hadoop-aws-3.1.2.jar
spark-select_2.11-2.1.jar

SparkContext conf:
(u'spark.driver.port', u'37271')
(u'spark.driver.memory', u'1G')
(u'spark.executor.id', u'driver')
(u'spark.driver.host', u'spark-driver')
(u'spark.executor.memory', u'1G')
(u'spark.rdd.compress', u'True')
(u'spark.master', u'spark://spark-master:7077')
(u'spark.app.id', u'app-20200604114415-0273')
(u'spark.serializer.objectStreamReset', u'100')
(u'spark.cores.max', u'1')
(u'spark.submit.deployMode', u'client')
(u'spark.app.name', u'select_test_1')
(u'spark.driver.maxResultSize', u'1G')
(u'spark.driver.cores', u'1')

script.py:
import os
import sys
import time

from pyspark import SparkContext, SparkConf, SQLContext
from pyspark.sql.types import *

conf = SparkConf()
conf.setMaster('spark://spark-master:7077')
sc = SparkContext(conf=conf)

hadoop_conf = sc._jsc.hadoopConfiguration()
hadoop_conf.set("fs.s3a.access.key", os.getenv('ACCESS_KEY_ID'))
hadoop_conf.set("fs.s3a.secret.key", os.getenv('SECRET_ACCESS_KEY'))
hadoop_conf.set("fs.s3a.endpoint", os.getenv('ENDPOINT_URL'))
hadoop_conf.set("fs.s3a.impl", "org.apache.hadoop.fs.s3a.S3AFileSystem")
hadoop_conf.set("fs.s3a.server-side-encryption.key", "")
hadoop_conf.set("fs.s3a.path.style.access", "true")
hadoop_conf.set("com.amazonaws.services.s3.enableV4", "true")
hadoop_conf.set("fs.s3a.retry.interval", "5s")

sql = SQLContext(sc)

for c in sc.getConf().getAll():
    print(c)

st2 = StructType([
        StructField("name", StringType(), True),
        StructField("age", IntegerType(), False),
        StructField("name2", StringType(), False),
    ])

df2 = sql \
        .read \
        .format('minioSelectParquet') \
        .schema(st2) \
        .load('s3://my_bucket/dev/parquet_test/spark_select_test/people2.parquet')

df2.show()
print("Done!")
print("Dataframe has", df2.count(), "lines!")

And traceback:
2020-06-04 11:44:17,390 INFO scheduler.DAGScheduler: Final stage: ResultStage 1 (showString at NativeMethodAccessorImpl.java:0)
2020-06-04 11:44:17,390 INFO scheduler.DAGScheduler: Parents of final stage: List()
2020-06-04 11:44:17,391 INFO scheduler.DAGScheduler: Missing parents: List()
2020-06-04 11:44:17,391 INFO scheduler.DAGScheduler: Submitting ResultStage 1 (MapPartitionsRDD[4] at showString at NativeMethodAccessorImpl.java:0), which has no missing parents
2020-06-04 11:44:17,392 INFO memory.MemoryStore: Block broadcast_1 stored as values in memory (estimated size 6.2 KB, free 413.9 MB)
2020-06-04 11:44:17,393 INFO memory.MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 3.3 KB, free 413.9 MB)
2020-06-04 11:44:17,394 INFO storage.BlockManagerInfo: Added broadcast_1_piece0 in memory on spark-master-headless:36549 (size: 3.3 KB, free: 413.9 MB)
2020-06-04 11:44:17,394 INFO spark.SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1163
2020-06-04 11:44:17,394 INFO scheduler.DAGScheduler: Submitting 1 missing tasks from ResultStage 1 (MapPartitionsRDD[4] at showString at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(1))
2020-06-04 11:44:17,394 INFO scheduler.TaskSchedulerImpl: Adding task set 1.0 with 1 tasks
2020-06-04 11:44:17,395 INFO scheduler.TaskSetManager: Starting task 0.0 in stage 1.0 (TID 1, 10.161.6.115, executor 1, partition 1, PROCESS_LOCAL, 8083 bytes)
2020-06-04 11:44:17,478 INFO storage.BlockManagerInfo: Added broadcast_1_piece0 in memory on 10.161.6.115:46823 (size: 3.3 KB, free: 413.9 MB)
2020-06-04 11:44:17,699 INFO scheduler.TaskSetManager: Finished task 0.0 in stage 1.0 (TID 1) in 304 ms on 10.161.6.115 (executor 1) (1/1)
2020-06-04 11:44:17,699 INFO scheduler.TaskSchedulerImpl: Removed TaskSet 1.0, whose tasks have all completed, from pool 
2020-06-04 11:44:17,700 INFO scheduler.DAGScheduler: ResultStage 1 (showString at NativeMethodAccessorImpl.java:0) finished in 0.309 s
2020-06-04 11:44:17,700 INFO scheduler.DAGScheduler: Job 1 finished: showString at NativeMethodAccessorImpl.java:0, took 0.310314 s
+-------+---+---------------+
|   name|age|          name2|
+-------+---+---------------+
|Michael| 31|Michael-Michael|
|   Andy| 30|      Andy-Andy|
| Justin| 19|  Justin-Justin|
+-------+---+---------------+

Done!
Traceback (most recent call last):
  File "/tmp/s3a_select.py", line 57, in <module>
    print("Dataframe has", df2.count(), "lines!")
  File "/spark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 523, in count
  File "/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o79.count.
: java.lang.ArrayIndexOutOfBoundsException: 0
	at io.minio.spark.select.SelectParquetRelation$$anonfun$getRows$1.apply(SelectParquetRelation.scala:105)
	at io.minio.spark.select.SelectParquetRelation$$anonfun$getRows$1.apply(SelectParquetRelation.scala:88)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at io.minio.spark.select.SelectParquetRelation.getRows(SelectParquetRelation.scala:88)
	at io.minio.spark.select.SelectParquetRelation.tokenRDD(SelectParquetRelation.scala:122)
	at io.minio.spark.select.SelectParquetRelation.buildScan(SelectParquetRelation.scala:134)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$10.apply(DataSourceStrategy.scala:293)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$10.apply(DataSourceStrategy.scala:293)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:326)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:325)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProjectRaw(DataSourceStrategy.scala:381)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProject(DataSourceStrategy.scala:321)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.apply(DataSourceStrategy.scala:289)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:78)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:75)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1334)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:75)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:67)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:78)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:75)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1334)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:75)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:67)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:73)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:69)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:78)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:78)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3365)
	at org.apache.spark.sql.Dataset.count(Dataset.scala:2835)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

2020-06-04 11:44:18,298 INFO spark.SparkContext: Invoking stop() from shutdown hook`
without spark-select code works as expected.

**Comment by harshavardhana** [comment]
Can you please attach your sample parquet file here? @ogerasymenko

**Comment by ogerasymenko** [comment]
@harshavardhana I upload it to my repo, because file in unsupported format
[https://github.com/ogerasymenko/airflow-test/blob/master/files/people2.parquet](url)

**Comment by ogerasymenko** [comment]
@harshavardhana any suggestions?

**Comment by harshavardhana** [comment]
> @harshavardhana any suggestions?

Not yet, busy at the moment will get back soon.

**Comment by ogerasymenko** [comment]
> > @harshavardhana any suggestions?
> 
> Not yet, busy at the moment will get back soon.

ok, thanks
