### ISSUE TITLE
Exception due to casting String

### ISSUE THREAD

**Issue by dgloeckner** [minio/spark-select#14]
Usingn the attached test data a `java.text.ParseException` is thrown.
[testdata.zip](https://github.com/minio/spark-select/files/4736274/testdata.zip)

```
spark.read.format("minioSelectParquet").schema(schema).load("s3://bucket/path").show
```

Resulting exception:
```
java.text.ParseException: Unparseable number: " while nice and all smiles"
  at java.text.NumberFormat.parse(NumberFormat.java:385)
  at io.minio.spark.select.util.TypeCast$$anonfun$castTo$4.apply$mcD$sp(TypeCast.scala:62)
  at io.minio.spark.select.util.TypeCast$$anonfun$castTo$4.apply(TypeCast.scala:62)
  at io.minio.spark.select.util.TypeCast$$anonfun$castTo$4.apply(TypeCast.scala:62)
  at scala.util.Try.getOrElse(Try.scala:79)
  at io.minio.spark.select.util.TypeCast$.castTo(TypeCast.scala:62)
  at io.minio.spark.select.SelectParquetRelation$$anonfun$getRows$1.apply(SelectParquetRelation.scala:106)
  at io.minio.spark.select.SelectParquetRelation$$anonfun$getRows$1.apply(SelectParquetRelation.scala:88)
  at scala.collection.Iterator$class.foreach(Iterator.scala:891)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at io.minio.spark.select.SelectParquetRelation.getRows(SelectParquetRelation.scala:88)
  at io.minio.spark.select.SelectParquetRelation.tokenRDD(SelectParquetRelation.scala:122)
  at io.minio.spark.select.SelectParquetRelation.buildScan(SelectParquetRelation.scala:134)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$10.apply(DataSourceStrategy.scala:293)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$10.apply(DataSourceStrategy.scala:293)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:326)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:325)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProjectRaw(DataSourceStrategy.scala:403)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProject(DataSourceStrategy.scala:321)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy.apply(DataSourceStrategy.scala:289)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
  at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
  at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
  at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:78)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:75)
  at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
  at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
  at scala.collection.Iterator$class.foreach(Iterator.scala:891)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
  at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
  at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1334)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:75)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:67)
  at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
  at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:73)
  at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:69)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:78)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:78)
  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3365)
  at org.apache.spark.sql.Dataset.head(Dataset.scala:2550)
  at org.apache.spark.sql.Dataset.take(Dataset.scala:2764)
  at org.apache.spark.sql.Dataset.getRows(Dataset.scala:254)
  at org.apache.spark.sql.Dataset.showString(Dataset.scala:291)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:751)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:710)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:719)
  ... 49 elided
```

**Comment by harshavardhana** [comment]
This looks like schema was wrong , can you attach the sample file and schema was used ?

**Comment by dgloeckner** [comment]
Sample file is attached already (zipped parquet) and the schema was derived from it.

**Comment by andraxin** [comment]
I'm guessing that the root cause for this _may be_ that, compared to S3Select, `org.apache.commons.csv.CSVParser` appears to have a very different idea  of how escape characters are supposed to work.  Setting escape to double quote (`"`) results in the following `IOException` (at least, for `commons-csv:1.8`):
```
java.io.IOException: (startline 3) EOF reached before encapsulated token finished
  at org.apache.commons.csv.Lexer.parseEncapsulatedToken(Lexer.java:288)
  at org.apache.commons.csv.Lexer.nextToken(Lexer.java:158)
  at org.apache.commons.csv.CSVParser.nextRecord(CSVParser.java:674)
  at org.apache.commons.csv.CSVParser.getRecords(CSVParser.java:628)
  ... 28 elided
```

<details>
<summary>Sample REPL session</summary>

```
~> scala -cp $(coursier fetch -p org.apache.commons:commons-csv:1.8)
Downloading https://repo1.maven.org/maven2/org/apache/commons/commons-csv/1.8/commons-csv-1.8.pom
Downloaded https://repo1.maven.org/maven2/org/apache/commons/commons-csv/1.8/commons-csv-1.8.pom
Downloading https://repo1.maven.org/maven2/org/apache/commons/commons-parent/50/commons-parent-50.pom
Downloaded https://repo1.maven.org/maven2/org/apache/commons/commons-parent/50/commons-parent-50.pom
Downloading https://repo1.maven.org/maven2/org/apache/apache/21/apache-21.pom
Downloaded https://repo1.maven.org/maven2/org/apache/apache/21/apache-21.pom
Downloading https://repo1.maven.org/maven2/org/apache/commons/commons-csv/1.8/commons-csv-1.8.jar
Downloaded https://repo1.maven.org/maven2/org/apache/commons/commons-csv/1.8/commons-csv-1.8.jar
Welcome to Scala 2.12.4-20171011-114433-c2a5883 (OpenJDK 64-Bit Server VM, Java 1.8.0_252).
Type in expressions for evaluation. Or try :help.

scala> import java.io.File
import java.io.File

scala> import java.nio.charset.Charset
import java.nio.charset.Charset

scala> import org.apache.commons.csv.{CSVParser,CSVFormat}
import org.apache.commons.csv.{CSVParser, CSVFormat}

scala> val file = new File("test.csv")
file: java.io.File = test.csv

scala> val p = CSVParser.parse(file,Charset.defaultCharset,CSVFormat.DEFAULT)
p: org.apache.commons.csv.CSVParser = org.apache.commons.csv.CSVParser@605d942c

scala> p.getRecords
res0: java.util.List[org.apache.commons.csv.CSVRecord] = [CSVRecord [comment='null', recordNumber=1, values=[# no header: serial,  comment,  S3Select,  CSVParser]], CSVRecord [comment='null', recordNumber=2, values=[1, :"escaped quote, no, yes]], CSVRecord [comment='null', recordNumber=3, values=[2, quoted, delimiter, no, yes]], CSVRecord [comment='null', recordNumber=4, values=[3, "escaped quote S3, yes, no]]]

scala> val pe = CSVParser.parse(file,Charset.defaultCharset,CSVFormat.DEFAULT.withEscape(':'))
pe: org.apache.commons.csv.CSVParser = org.apache.commons.csv.CSVParser@2e292fbe

scala> pe.getRecords
res1: java.util.List[org.apache.commons.csv.CSVRecord] = [CSVRecord [comment='null', recordNumber=1, values=[# no header: serial,  comment,  S3Select,  CSVParser]], CSVRecord [comment='null', recordNumber=2, values=[1, "escaped quote, no, yes]], CSVRecord [comment='null', recordNumber=3, values=[2, quoted, delimiter, no, yes]], CSVRecord [comment='null', recordNumber=4, values=[3, "escaped quote S3, yes, no]]]

scala> val peq = CSVParser.parse(file,Charset.defaultCharset,CSVFormat.DEFAULT.withEscape('"'))
peq: org.apache.commons.csv.CSVParser = org.apache.commons.csv.CSVParser@a23f9ff

scala> peq.getRecords
java.io.IOException: (startline 3) EOF reached before encapsulated token finished
  at org.apache.commons.csv.Lexer.parseEncapsulatedToken(Lexer.java:288)
  at org.apache.commons.csv.Lexer.nextToken(Lexer.java:158)
  at org.apache.commons.csv.CSVParser.nextRecord(CSVParser.java:674)
  at org.apache.commons.csv.CSVParser.getRecords(CSVParser.java:628)
  ... 28 elided
```
</details>

<details>
<summary>test.csv (since CSV attachments are not supported here)</summary>

```csv
# no header: serial, comment, S3Select, CSVParser
1,:"escaped quote,no,yes
2,"quoted, delimiter",no,yes
3,"""escaped quote S3",yes,no
```
</details>

BTW, the same simple test file is also useful for testing the ineffectiveness of `.option("header",..)`.
See issue #16...
