### ISSUE TITLE
java.lang.NoSuchMethodError: com.amazonaws.services.s3.model.InputSerialization.setParquet(Lcom/amazonaws/services/s3/model/ParquetInput;)

### ISSUE THREAD

**Issue by vinay-kl** [minio/spark-select#7]
I'm trying to read from the 's3' source and the format is parquet.

**spark-shell --packages io.minio:spark-select_2.11:2.1**

While performing the following operation, I slipped into the error below

`spark.read.format("minioSelectParquet").schema(df_nr.schema).load("s3://path).filter(col("event_type").isin("Banner` Load","Banner Child Load","banner-click","banner-child-click","streamCardLoad","streamCardChildLoad","streamCardClick","stream-card-child-click","streamCardChildClick")).count()`

**df_nr.schema** is my normal spark df.schema

java.lang.NoSuchMethodError: com.amazonaws.services.s3.model.InputSerialization.setParquet(Lcom/amazonaws/services/s3/model/ParquetInput;)V
  at io.minio.spark.select.Select$$anon$1.<init>(Select.scala:97)
  at io.minio.spark.select.Select$.requestParquet(Select.scala:84)
  at io.minio.spark.select.SelectParquetRelation$$anonfun$getRows$1.apply(SelectParquetRelation.scala:91)
  at io.minio.spark.select.SelectParquetRelation$$anonfun$getRows$1.apply(SelectParquetRelation.scala:88)
  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
  at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
  at io.minio.spark.select.SelectParquetRelation.getRows(SelectParquetRelation.scala:88)
  at io.minio.spark.select.SelectParquetRelation.tokenRDD(SelectParquetRelation.scala:122)
  at io.minio.spark.select.SelectParquetRelation.buildScan(SelectParquetRelation.scala:134)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$10.apply(DataSourceStrategy.scala:293)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$10.apply(DataSourceStrategy.scala:293)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:338)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:337)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProjectRaw(DataSourceStrategy.scala:415)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProject(DataSourceStrategy.scala:333)
  at org.apache.spark.sql.execution.datasources.DataSourceStrategy.apply(DataSourceStrategy.scala:289)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:63)
  at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
  at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
  at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:78)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:75)
  at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
  at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
  at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
  at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:75)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:67)
  at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
  at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:78)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:75)
  at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
  at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
  at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
  at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:75)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:67)
  at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
  at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
  at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:93)
  at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:72)
  at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:68)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:77)
  at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:77)
  at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3248)
  at org.apache.spark.sql.Dataset.count(Dataset.scala:2769)

I'm guessing its aws-sdk mismastch issue. this is the log I got while I executed spark-shell.
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
	confs: [default]
	found io.minio#spark-select_2.11;2.1 in central
	found com.amazonaws#aws-java-sdk;1.11.434 in central
	found com.amazonaws#aws-java-sdk-signer;1.11.434 in central
	found com.amazonaws#aws-java-sdk-core;1.11.434 in central
:: resolution report :: resolve 3440ms :: artifacts dl 43ms
	:: modules in use:
	com.amazonaws#aws-java-sdk;1.11.434 from central in [default]
	com.amazonaws#aws-java-sdk-acm;1.11.434 from central in [default]

Please let me know your thoughts on this.

**Comment by vinay-kl** [comment]
The Initial issue was with the **fs.s3a.region**, this one is set to the default **us-east-1**, I changed it to our own region.

**Comment by harshavardhana** [comment]
This clearly looks like your aws-sdk-java is older here can you provide all the library versions? That you might have locally

**Comment by vinay-kl** [comment]
The default version is 1.11.297 in EMR. even if I specify ** --packages com.amazonaws:aws-java-sdk-s3:1.11.434**. all the aws-sdk related jars are being referenced to 1.11.297
`spark-shell --packages com.amazonaws:aws-java-sdk-s3:1.11.434`
`import com.amazonaws.services.s3.model.InputSerialization`
`new InputSerialization().getClass.getResource("InputSerialization.class")`
`res0: java.net.URL = jar:file:/usr/share/aws/aws-java-sdk/aws-java-sdk-s3-1.11.297.jar!/com/amazonaws/services/s3/model/InputSerialization.class`

**Comment by harshavardhana** [comment]
That's what it looks like, let me how we can update this forcefully.

**Comment by vinay-kl** [comment]
I'm not sure, I was hoping you'd shed some light on this.
I will try to resolve this and let you know, in the meantime if you are able to find a solution please revert back.

**Comment by harshavardhana** [comment]
> I'm not sure, I was hoping you'd shed some light on this.

I meant I am going to look for a way to do this.

**Comment by harshavardhana** [comment]
It is likely a classpath issue if you have multiple versions of aws-sdk-java - you would have to address your classpath.

**Comment by vinay-kl** [comment]
the error didn't occur with the new EMR version which comes with spark 2.4.0.
but will minio spark select works with spark 2.4.0? I'm encountering **Error parsing parquet file**

**Comment by harshavardhana** [comment]
Yes it will work fine, parquet parsing happens on server. What server are you using?

**Comment by kannappanr** [comment]
ping @vinay-kl

**Comment by harshavardhana** [comment]
> Yes it will work fine, parquet parsing happens on server. What server are you using?

Closing this issue as stale, please re-open if you have more details.
